name: ci
on:  
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  build:
    name: run python tests
    runs-on: ubuntu-latest
 
    steps:
 
    - uses: actions/checkout@v2
 
    - name: setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC
 
    - name: set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
 
    - name: install python dependencies
      run: |
        sudo apt-get install -y $(grep -o ^[^#][[:alnum:]-]* "packages.list")
        python3 -m pip install --upgrade pip
        pip3 install .
        pip3 install pytest pytest-cov

    - name: list directory 
      run: |
        pwd
        ls

    - name: test with pytest
      run: |
        pytest --exitfirst --verbose --failed-first \
        --cov=. --cov-report html
      working-directory: .
